### ISSUE TITLE
After uploading the .exe file, "There was an error while processing your request: [WinError 2] He cannot find the specified file"

### ISSUE THREAD

**Issue by VladislavKont** [Picovoice/pvrecorder#103]
After packaging the project in .exe, the PvRecorder library returns the error "There was an error while processing your request: [WinError 2] He cannot find the specified file". The fact is that I added markers to the program code and found that the error occurs precisely on the line:
recorder = PvRecorder(frame_length=512, device_index=dev_mic)
recorder.start()
dev_mic = 0 or dev_mic = 1
In Python itself, the code works without problems.
It is suspected that the library is not packaged in a package run by the pyinstaller --noconsole --onefile -i='.\icon.ico' --collect-all command app.py . We need your help in solving the problem

**Comment by VladislavKont** [comment]
Indeed, the library was not included in the exe package, it was necessary to additionally specify the library name in the configuration. Thanks you!

**Comment by ErisMik** [comment]
Glad you could get it figured out!
