### ISSUE TITLE
Which case `IOError` happens?

### ISSUE THREAD

**Issue by eouia** [Picovoice/pvrecorder#111]
I'm using NodeJS package. 
Recently, I encountered `PvRecorderStatusIOError: PvRecorder failed to read audio data frame.` 
However, I cannot guess what caused this error. 
I just want to understand generally what this error message means, not for direct debugging my code.
What are the possible reasons/cases this error happens?

**Comment by ksyeo1010** [comment]
this happens when you are not reading anything, or have nothing to read. Make sure to follow docs properly https://github.com/Picovoice/pvrecorder/tree/main/binding/nodejs, i.e. call `start` before you call `read`
