### ISSUE TITLE
Getting an Overflow Issue on a Raspberry Pi

### ISSUE THREAD

**Issue by kingofsquirrel** [Picovoice/pvrecorder#27]
Hey, so I wrote some code on my windows machine to detect a wakeword using pvporcupine and pvrecorder, and I've now just moved on to a Raspberry Pi and whenever I run my script it spams the terminal with 
**Overflow - reader is not reading fast enough**
I have had this problem before, although the issue back then was that I was running multiple recorders at the same time, which I am not right now.

```
import pvporcupine
from pvrecorder import PvRecorder 

porcupine = None
recorder = None
accesskey = "my access key"


try:
    porcupine = pvporcupine.create(access_key = accesskey, keywords=['computer'])
    recorder = PvRecorder(device_index = 0, frame_length = porcupine.frame_length)
    recorder.start()

    while True:
        pcm = recorder.read()
         
        result = porcupine.process(pcm)
        if(result >= 0):
            print("Keyword detected")
            recorder.stop()
            
except pvporcupine.PorcupineInvalidArgumentError as e:
    print("One or more arguments provided to Procupine is invalid!")
    raise e
except pvporcupine.PorcupineActivationError as e:
    print("Accesskey denied.")
    raise e
except pvporcupine.PorcupineActivationLimitError as e:
    print("Accesskey has reached it's temporary device limit.")
    raise e
except pvporcupine.PorcupineActivationRefusedError as e:
    print("Accesskey refused.")
    raise e
except pvporcupine.PorcupineActivationThrottledError as e:
    print("Accesskey has been throttled.")
    raise e
except pvporcupine.PorcupineError as e:
    print("Failed to initialize Porcupine.")
    raise e
except KeyboardInterrupt:
    print("Stopping")
finally:
    if porcupine is not None:
        porcupine.delete()
    if recorder is not None:
        recorder.delete()
```

I have no idea why I'm getting an overflow error, as I said it works just fine on Windows but not on my raspberry pi.

**Comment by kenarsa** [comment]
what version of RPI?

**Comment by kingofsquirrel** [comment]
I'm using Raspberry Pi 3 Model B and the Raspberry Pi OS version 11

**Comment by kenarsa** [comment]
OK. I thought the possible cause is that porcupine is not processing fast enough which is possible on RPI0. But RPI3 is super fast. Can you please try to reproduce this with [official porcupine mic demo](https://github.com/Picovoice/porcupine/tree/master/demo/python#microphone-demo)? Then, I can debug more.

**Comment by kingofsquirrel** [comment]
When I try to run the official demo, it gives me another error:

```
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
Traceback (most recent call last):
  File "/usr/local/bin/porcupine_demo_mic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/pvporcupinedemo/porcupine_demo_mic.py", line 219, in main
    PorcupineDemo(
  File "/usr/local/lib/python3.9/dist-packages/pvporcupinedemo/porcupine_demo_mic.py", line 90, in run
    recorder = PvRecorder(device_index=self._input_device_index, frame_length=porcupine.frame_length)
  File "/usr/local/lib/python3.9/dist-packages/pvrecorder/pvrecorder.py", line 78, in __init__
    raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to initialize pv_recorder.")
RuntimeError: Failed to initialize pv_recorder.
```

**Comment by kenarsa** [comment]
I don't exactly what's going on with your RPI. But my suggestion is to reset it, make sure you are not recording already, have a working mic connected, and then try the demo. if that fails then try to record yourself with your mic using ALSA and see if that works.

**Comment by kingofsquirrel** [comment]
I did a complete RPI reset, still didn't work, although I did get it working using PyAudio. Mabye PvRecorder just doesn't accept my microphone?

**Comment by ibebbs** [comment]
Interestingly, I'm encountering exactly this issue when using PvRecorder from a .NET 6.0 app; also on a Raspberry Pi 3 using a I2S microphone which is configured through ALSA (e.g. `arecord -D dmic_sv -c2 -r 44100 -f S32_LE -t wav -v file.wav` works fine).

There is a minimal repoduction in [this repo](https://github.com/ibebbs/PvRecorderSpike). It can be compiled for and copied to the RPi3 using:

```
dotnet publish --runtime linux-arm -c Release --self-contained
scp -r ./bin/Release/net6.0/linux-arm/publish/* pi@[RPi IP Address]:~/PvRecorderSpike/
```

Then from the Pi (usually via an SSH session), setting execute permissions and running the spike using:

```
cd ~/PvRecorderSpike/
chmod +x PvRecorderSpike
chmod +x ./scripts/*
./PvRecorderSpike
```

I then see a screen full of output alternating between the overflow message and successfully reading data:

```
Overflow - reader is not reading fast enough.
Overflow - reader is not reading fast enough.
Overflow - reader is not reading fast enough.
Read 1024 bytes
Overflow - reader is not reading fast enough.
Overflow - reader is not reading fast enough.
Read 1024 bytes
Overflow - reader is not reading fast enough.
Overflow - reader is not reading fast enough.
Overflow - reader is not reading fast enough.
```

Would be great to use PvRecorder rather than having to source another audio input library so very interested to see if this can be resolved.

Thanks

**Comment by kenarsa** [comment]
@ibebbs can you create a new issue for this? It is hard to manage 2 in one thread! I cant help out by going through your repo. what I am happy to do is debug the demo app if you can reproduce using that. thanks!

**Comment by ibebbs** [comment]
@kenarsa I would be happy to create a new issue but this seems an odd request given that - platform aside - it's the exact same underlying problem.

Regardless, I have resolved the issue. For @kingofsquirrel's benefit: It seems passing a specific audio device index is not supported. Changing this:

```
using (PvRecorder recorder = PvRecorder.Create(0, frameLength: 1024))
```

to this (note the '-1' parameter for device index):

```
using (PvRecorder recorder = PvRecorder.Create(-1, frameLength: 1024))
```

resulted in PvRecorder successfully reading from the [default/first] audio device.

**Comment by kenarsa** [comment]
@ibebbs good point and I think you could be right re the issue @kingofsquirrel is experiencing. @kingofsquirrel can you confirm a resolution?

**Comment by kingofsquirrel** [comment]
@ibebbs Thank you very much, using -1 instead of 0 did indeed solve my problem. Still weird that it works with 0 on a Windows machine but a RPI requires -1.
