### ISSUE TITLE
Get audio devices not listing all devices available

### ISSUE THREAD

**Issue by l-jaynes** [Picovoice/pvrecorder#28]
### Expected behaviour
pvrecorder lists the same devices that the underlying miniaudio library can list

### Actual behaviour
pvrecord only lists a subset of the actual devices on my machine

### Detailed description
Running the pvrecorder using the Rust SDK on a Raspberry pi 4B.

There seems to be an issue with the pvrecorder finding all the devices I have set up using Alsa. Digging around your SDK it looks like you are using miniaudio on the backend so I took the time to see if it was a miniaudio issue or something with pvrecorder.

Here are my results with miniaudio:
```
Capture Devices:
0: "Discard all samples (playback) or generate zero samples (capture)"
1: "JACK Audio Connection Kit"
2: "PulseAudio Sound Server"
3: l1ch0 input
4: l1ch1 input
5: default
6: USB Audio Codec, USB Audio
```

Here are my results with the pvrecorder:
```
index: 0, device name: "Discard all samples (playback) or generate zero samples (capture)"
index: 1, device name: "JACK Audio Connection Kit"
index: 2, device name: "PulseAudio Sound Server"
```

As you can see the pvrecorder stops listing the devices at the 2nd index while miniaudio finds all 7 of my devices available.

**Comment by kenarsa** [comment]
just looking into this [section of the code](https://github.com/Picovoice/pvrecorder/blob/main/src/pv_recorder.c#L276-L288) I think we get everything. Do you mind putting some logging to see if my assumption is correct on your device?

**Comment by l-jaynes** [comment]
Would you mind sending me a snippet of the logging you had in mind for that section of code? I put some of my own in but everything seems to line up with original output. Thanks.

**Comment by ksyeo1010** [comment]
We have investigated the issue and we will be releasing a fix in the coming weeks.

**Comment by l-jaynes** [comment]
That doesn't seem to have solved the issue.

Here are the results from the new pvrecorder version:

`root@lab:~/Git/pvrecorder/build# ./demo --show_audio_devices
pv_recorder version: v1.1.0
Printing devices...
index: 0, name: Discard all samples (playback) or generate zero samples (capture)
index: 1, name: JACK Audio Connection Kit
index: 2, name: PulseAudio Sound Server`

Here is the result from miniaudio:

`root@lab:~/Git/miniaudio/examples# ./enumeration
Playback Devices
    0: Discard all samples (playback) or generate zero samples (capture)
    1: JACK Audio Connection Kit
    2: PulseAudio Sound Server
    3: N l1 audio device
    4: N l2 audio device
    5: N l1ch1 input
    6: N l1ch2 input
    7: N l2ch1 input
    8: N l2ch2 input
    9: USB AUDIO  CODEC, USB Audio
    10: USB AUDIO  CODEC, USB Audio

Capture Devices
    0: Discard all samples (playback) or generate zero samples (capture)
    1: JACK Audio Connection Kit
    2: PulseAudio Sound Server
    3: N lane 1 audio device
    4: N lane 2 audio device
    5: N l1ch1 input
    6: N l1ch2 input
    7: N l2ch1 input
    8: N l2ch2 input
    9: USB AUDIO  CODEC, USB Audio
    10: USB AUDIO  CODEC, USB Audio
    
pvrecorder still seems to be missing most of available devices.

**Comment by ksyeo1010** [comment]
did you build and run the c demo? if so can you make sure you ran `git submodule update --init --recursive` in the repo?

**Comment by l-jaynes** [comment]
Alright cool. I cleaned out the repo and started fresh and it seems to being working now.

```
root@lab:~/Git/pvrecorder/build# ./demo --show_audio_devices
pv_recorder version: v1.1.0
Printing devices...
index: 0, name: Discard all samples (playback) or generate zero samples (capture)
index: 1, name: JACK Audio Connection Kit
index: 2, name: PulseAudio Sound Server
index: 3, name: N lane 1 audio device
index: 4, name: N lane 2 audio device
index: 5, name: N l1ch1 input
index: 6, name: N l1ch2 input
index: 7, name: N l2ch1 input
index: 8, name: N l2ch2 input
index: 9, name: USB AUDIO  CODEC, USB Audio
index: 10, name: USB AUDIO  CODEC, USB Audio
```
To get it to work on the raspberry pi I did need to add `-latomic` to the cmake flags. Not sure if that's something new with miniaudio but may be worth looking into.

`set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fvisibility=hidden -latomic")`

**Comment by ksyeo1010** [comment]
https://github.com/Picovoice/pvrecorder/pull/32 will fix the build. Will close the issue since it is now resolved.
