### ISSUE TITLE
Raspberry pi CM4 Overflow error

### ISSUE THREAD

**Issue by limitbit** [Picovoice/pvrecorder#39]
I try to make a quick test with raspberry pi CM4 with "ReSpeaker 2-Mics" and follow the [documents ](https://picovoice.ai/docs/quick-start/picovoice-c/)to build "picovoice_demo_mic" it is build with success unfortunately not working as expected.

It returns many "Overflow - reader is not reading fast enough" in a second until i break the app.

I tried all capture devices but no luck, here is my device list 

index: 0, name: Discard all samples (playback) or generate zero samples (capture)
index: 1, name: JACK Audio Connection Kit
index: 2, name: PulseAudio Sound Server
index: 3, name:

My device is working and i am able to use picovoice with asoundlib (capture hardware 0,0)

**Comment by ksyeo1010** [comment]
We have updated the C demos. Can you give it a try again with a clean build. When you run the demo make sure you update the submodules with `git submodule update --init --recursive`.

**Comment by limitbit** [comment]
@ksyeo1010  if we are talking to rebuild picovoice c demos, now it is not building. I remove picovoice directory and reinstall repo and try to build with 
cmake -S demo/c/. -B demo/c/build && cmake --build demo/c/build --target picovoice_demo_mic

Now i get  "/root/picovoice/demo/c/pvrecorder  does not contain a CMakeLists.txt file. " error. :)

**Comment by ksyeo1010** [comment]
can you check if `demo/c/pvrecorder` directory is not empty, if it is, update the submodules with `git submodule update --init --recursive`.

**Comment by limitbit** [comment]
ok i update the submodules and rebuild picovoice now it is working.
