### ISSUE TITLE
'No such file or directory' when file path contains a space

### ISSUE THREAD

**Issue by ReeceKenney** [Picovoice/pvrecorder#44]
Hello, I copied/pasted the source code from the [mic.js demo](https://github.com/Picovoice/picovoice/blob/master/demo/nodejs/mic.js) and when I ran it, I saw the error:

`/bin/sh: /Users/reecekenney/Documents/Virtual: No such file or directory`

It's coming from this line:

`const PvRecorder = require("@picovoice/pvrecorder-node");`

Because even if I remove all lines other than that line, I still see the error. 

The issue is that the path to my file contains a space:

`'/Users/reecekenney/Documents/Virtual Assistant/myProject/app.js'`

**Comment by mrrostam** [comment]
Thanks for reporting this. 

I've pushed a new package with a patch, could you update `pvrecorder` library to [v1.1.1](https://www.npmjs.com/package/@picovoice/pvrecorder-node) and let me know if that resolves the issue?

**Comment by ReeceKenney** [comment]
Thanks so much for the quick action on this! I've upgraded and I now see this error:

```
node:internal/modules/cjs/loader:361
      throw err;
      ^
Error: Cannot find module '/Users/reecekenney/Documents/Virtual Assistant/myProject/node_modules/@picovoice/pvrecorder-node/index.js'. Please verify that the package.json has a valid "main" entry
```

I tried deleting the node modules folder and reinstalling the packages but no luck. I also tried it in a different repo and saw the same issue. It could definitely be something I'm doing wrong here, but do you have any ideas?

**Comment by mrrostam** [comment]
No! that was a packaging issue that is fixed in the new released version of [@picovoice/pvrecorder-node](https://www.npmjs.com/package/@picovoice/pvrecorder-node/v/1.1.2). Sorry about it! can you give it another try and let me know if everything works fine?

**Comment by ReeceKenney** [comment]
Just tried the new version and everything is working as expected! Thank you so much for the help and quick resolution on this!
