### ISSUE TITLE
pvrecorder no longer runs from a systemd service on pi bullseye (os ver 11)

### ISSUE THREAD

**Issue by lfg6000** [Picovoice/pvrecorder#46]
**Issue**
- on pi buster/v10 with python 3.7.3  i am able to run my porcupine wake work app in a systemd service
- on pi buster/v11 with python 3.9.2  i am not able to run my porcupine wake work app in a systemd service

**Testing the porcupine demo app on pi bullseye/v11 with python 3.9.2 as an app (works perfectly)**
- on pi bullseye/v11 with python 3.9.2 i am _able to run_ the porcupine demo from the cmd line using
> ~/lfg_work/PA_PorcupineDemo/venv/bin/python3  ~/lfg_work/PA_PorcupineDemo/venv/lib/python3.9/site-packages/pvporcupinedemo/porcupine_demo_mic.py --access_key myAccessKey --keywords picovoice
- pip3 install pvporcupinedemo into the venv
- it works perfectly  
   Using device: %s USB PnP Sound Device Mono,  Listening { picovoice (0.50)},   [2023-01-10 14:49:37.396491] Detected picovoice

**Testing the porcupine demo app on pi bullseye/v11 with python 3.9.2 as a systemd service (does not work)**
- on pi bullseye/v11 with python 3.9.2 i am not able to run the porcupine demo in a systemd service
- here is the unit file (i also tried User=usrnm and Group=audio)

[Unit]
Description=Porupine Demo Service Test
After=network-online.target
[Service]
Type=idle
StandardOutput=journal+console
WorkingDirectory=/home/[usrnm]/lfg_work/PA_PorcupineDemo
ExecStart=/home/[usrnm]/lfg_work/PA_PorcupineDemo/venv/bin/python3  -u /home/[usrnm]/lfg_work/PA_PorcupineDemo/venv/lib/python3.9/site-packages/pvporcupinedemo/porcupine_demo_mic.py --access_key 'myAccessKey' --keywords picovoice
[Install]
WantedBy=multi-user.target

- journal log with error
Jan 10 14:09:47.017665 lg4pi systemd[1]: Started Porupine Demo Service Test.
Jan 10 14:09:47.245102 lg4pi python3[25330]: **ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave**
Jan 10 14:09:47.246918 lg4pi python3[25330]: ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
Jan 10 14:09:47.248494 lg4pi python3[25330]: ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
Jan 10 14:09:47.250452 lg4pi python3[25330]: Traceback (most recent call last):
Jan 10 14:09:47.250452 lg4pi python3[25330]:   File "/home/[usrnm]/lfg_work/PA_PorcupineDemo/venv/lib/python3.9/site-packages/pvporcupinedemo/porcupine_demo_mic.py", line 231, in <module>
Jan 10 14:09:47.251232 lg4pi python3[25330]:     main()
Jan 10 14:09:47.251232 lg4pi python3[25330]:   File "/home/[usrnm]/lfg_work/PA_PorcupineDemo/venv/lib/python3.9/site-packages/pvporcupinedemo/porcupine_demo_mic.py", line 220, in main
Jan 10 14:09:47.251788 lg4pi python3[25330]:     PorcupineDemo(
Jan 10 14:09:47.251788 lg4pi python3[25330]:   File "/home/j[usrnm]/lfg_work/PA_PorcupineDemo/venv/lib/python3.9/site-packages/pvporcupinedemo/porcupine_demo_mic.py", line 90, in run
Jan 10 14:09:47.251788 lg4pi python3[25330]:     recorder = PvRecorder(device_index=self._input_device_index, frame_length=porcupine.frame_length)
Jan 10 14:09:47.251788 lg4pi python3[25330]:   File "/home/[usrnm]/lfg_work/PA_PorcupineDemo/venv/lib/python3.9/site-packages/pvrecorder/pvrecorder.py", line 81, in __init__
Jan 10 14:09:47.254323 lg4pi python3[25330]:     **raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to initialize pv_recorder.")**
Jan 10 14:09:47.254323 lg4pi python3[25330]: RuntimeError: Failed to initialize pv_recorder.
Jan 10 14:09:47.277661 lg4pi systemd[1]: PA_PorcupineDemo.service: Main process exited, code=exited, status=1/FAILURE
Jan 10 14:09:47.278021 lg4pi systemd[1]: PA_PorcupineDemo.service: Failed with result 'exit-code'.

**Error Analysis**
- ALSA lib pcm_dsnoop.c:638:(snd_pcm_dsnoop_open) unable to open slave
  looks like an access error to alsa from a systemd service?  a permissions issue?
- RuntimeError: Failed to initialize pv_recorder.
  i am not sure why this line throws and error:
    recorder = PvRecorder(device_index=self._input_device_index, frame_length=porcupine.frame_length)
    which invokes   status = init_func(device_index, frame_length,...)

**Conclusions**
- porcupine wake word is awesome so i would very much like to find a fix because i need to upgrade to from buster/v10 to bulleyse/v11
- admittedly this is looking like a difference between buster and bullseye
- i am hoping you can try the porcupine demo as a systemd service to see what is going on
- i am hoping you have some suggestions, i would be happy to try them

**Comment by mrrostam** [comment]
The main problem is working with ALSA as the root user; you probably would get the same error by executing `sudo porcupine_demo_mic --access_key 'myAccessKey' --keywords picovoice`; It's reported that it's a mix of design and permission problems but that is beyond the `pvrecorder` package.

However, A workaround would be creating the systemd service for a normal user instead of root; with this method , I was able to run Porcupine as a service without any issues on Bullseye/v11 with python 3.9.2. So

**Comment by lfg6000** [comment]
Thank you. Using a user systemd service fixed the issue. Thanks for the very quick reply.
This is great, the porcupine wake word based app now runs on pi bullseye/v11 and is started at boot.

I needed the nudge to learn about user systemd services because putting a User=[usr] in the root systemd unit file was not enough to get past ALSA design/permissions issues in bullseye/v11.  

in case anyone is interested here is what i ended up with...

**the steps to create a pi user systemd service that starts a boot (that also sends prints to the journal unbuffered)**

- put the systemd unit file in /home/[user]/.config/systemd/user

- example user systemd unit file
[Unit]
Description=PA_VoiceCmdService - listens for voice cmds and sends cmds to broker --user service.
[Service]
Type=idle
StandardOutput=journal+console
WorkingDirectory=/home/[usr]/lfg_work/PA_VoiceCmdService
ExecStart=/home/[usr]/lfg_work/PA_VoiceCmdService/venv/bin/python3.9 -u /home/[usr]/lfg_work/PA_VoiceCmdService/vcsApp.py
Restart=always
RestartSec=5
KillMode=process
TimeoutSec=infinity
[Install]
WantedBy=default.target

- run this cmd one time so that the user systemd service runs at boot (it creates a file in /var/lib/systemd/linger)
>sudo loginctl enable-linger [usr]  

**notes**
- note WantedBy can not be set to multi-user.target because it is not supported for user systemd services
- if you accidentally end up with a multi-user.target.wants file in  /home/[user]/.config/systemd/user it must be deleted/renamed or the service will not start at boot

**user systemd cmds and cmds to view the journal**
alias vcsrelo='systemctl --user daemon-reload'
alias vcsdisa='systemctl --user disable PA_VoiceCmdService.service'
alias vcsstop='systemctl --user stop    PA_VoiceCmdService.service'
alias vcsenab='systemctl --user enable  PA_VoiceCmdService.service'
alias vcsstar='systemctl --user start   PA_VoiceCmdService.service'
alias vcsstat='systemctl --user status  PA_VoiceCmdService.service'
alias vcsrest='systemctl --user restart PA_VoiceCmdService.service'
alias vcsjour='journalctl --user -o short-precise -u PA_VoiceCmdService.service'
alias vcsjouf='journalctl --user -o short-precise -f -u PA_VoiceCmdService.service'

**Comment by cinderblock** [comment]
> The main problem is working with ALSA as the root user; you probably would get the same error by executing `sudo porcupine_demo_mic --access_key 'myAccessKey' --keywords picovoice`; It's reported that it's a mix of design and permission problems but that is beyond the `pvrecorder` package.

@mrrostam Where are you seeing this? What working with ALSA as root user issues are you talking about?

**Comment by mrrostam** [comment]
> > The main problem is working with ALSA as the root user; you probably would get the same error by executing `sudo porcupine_demo_mic --access_key 'myAccessKey' --keywords picovoice`; It's reported that it's a mix of design and permission problems but that is beyond the `pvrecorder` package.
> 
> @mrrostam Where are you seeing this? What working with ALSA as root user issues are you talking about?

Somewhere on the raspberry pi forums, but you don't need to take my word for it; just run `porcupine_demo_mic --access_key 'myAccessKey' --keywords picovoice` as a normal user and as root and see the difference.
