### ISSUE TITLE
Problem debugging pvrecorder failure

### ISSUE THREAD

**Issue by rickmini** [Picovoice/pvrecorder#48]
I have been using picovoice  for over a year
I am using pycharm to program and have a number of programs that have been running on 3 different windows 11 machines
They all run well, they all use pvrecorder, pvrhino, pvporcupine 
I just replaced my old HP laptop with a new HP laptop Omen 16 12 gen intel, intel mic array with 2 mics (similar setup to old laptop)
but no matter what i  do the code that runs on 2 other windows 11 machines wont run on my new laptop. It always fails at   recorder = PvRecorder(device_index=-1, frame_length=512)

- I am using the latest versions of all 3 librarys
- I have tried with index 0, -1 and with a usb mike and index 1 Nothing works
- I can use the windows recorder to record my voice and it works fine with any mike i choose

I dont get any more explanation than RuntimeError: Failed to initialize pv_recorder.
Can you suggest anything i can try to figure out what the problem is.
I use my laptop as my main programming machine and i would like to figure this out. I can use 2 other machines to get this to work, but those are testing picovoice rhino on 2 different robots.
Hopefully you can give me some directiion to debug this.
Thanks

code:

from pvrecorder import PvRecorder
def main():
    recorder = PvRecorder(device_index=-1, frame_length=512)
    recorder.start()
    input("press a key")
    if recorder is not None:
        recorder.delete()
		
		
output:	
C:\Users\rickm\PycharmProjects\BaseProject\venv\Scripts\python.exe D:\____DEV2\PycharmProjects\RobotDev\test_pvrecorder.py 
Traceback (most recent call last):
  File "D:\____DEV2\PycharmProjects\RobotDev\test_pvrecorder.py", line 9, in <module>
    main()
  File "D:\____DEV2\PycharmProjects\RobotDev\test_pvrecorder.py", line 3, in main
    recorder = PvRecorder(device_index=-1, frame_length=512)
  File "C:\Users\rickm\PycharmProjects\BaseProject\venv\lib\site-packages\pvrecorder\pvrecorder.py", line 81, in __init__
    raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to initialize pv_recorder.")
RuntimeError: Failed to initialize pv_recorder.

**Comment by ErisMik** [comment]
Hi @rickmini,

`pvrecorder`  uses a library called [miniaudio](https://github.com/mackron/miniaudio) under the hood to handle the system audio. The error you are seeing is `pvrecorder` handling an error from `miniaudio`. Most likely `miniaudio` does not support your exact hardware / software configuration.

To start could you clone this repository, run the following commands in the [sdk/python](https://github.com/Picovoice/pvrecorder/tree/main/sdk/python) directory and report back the output you get here?
```console
python3 setup.py sdist bdist_wheel
python3 demo.py --show_audio_devices
```

You may need to install the python `wheel` package to run the first command: 
```console
pip3 install wheel
```

**Comment by rickmini** [comment]
Thanks for your quick response . ill give it a try


On March 1, 2023, at 6:58 PM, Eric Mikulin ***@***.***> wrote:

Hi @rickmini,

pvrecorder uses a library called miniaudio under the hood to handle the system audio. The error you are seeing is pvrecorder handling an error from miniaudio. Most likely miniaudio does not support your exact hardware / software configuration.

To start could you clone this repository, run the following commands in the sdk/python directory and report back the output you get here?

python3 setup.py sdist bdist_wheel python3 demo.py --show_audio_devices

You may need to install the python wheel package to run the first command:

pip3 install wheel

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/Picovoice/pvrecorder/issues/48#issuecomment-1451050996">https://github.com/Picovoice/pvrecorder/issues/48#issuecomment-1451050996</a>", "url": "<a href="https://github.com/Picovoice/pvrecorder/issues/48#issuecomment-1451050996">https://github.com/Picovoice/pvrecorder/issues/48#issuecomment-1451050996</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by rickmini** [comment]
Not sure what this tells us, but here are the results:

(venv) PS
C:\Users\rickm\Downloads\pvrecorder-main\pvrecorder-main\sdk\python> python
demo.py
Traceback (most recent call last):
  File
"C:\Users\rickm\Downloads\pvrecorder-main\pvrecorder-main\sdk\python\demo.py",
line 77, in <module>
    main()
  File
"C:\Users\rickm\Downloads\pvrecorder-main\pvrecorder-main\sdk\python\demo.py",
line 49, in main
    recorder = PvRecorder(device_index=device_index, frame_length=512)
  File
"C:\Users\rickm\Downloads\pvrecorder-main\pvrecorder-main\sdk\python\pvrecorder\pvrecorder.py",
line 82, in __init__
    raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to
initialize pv_recorder.")
RuntimeError: Failed to initialize pv_recorder.
(venv) PS
C:\Users\rickm\Downloads\pvrecorder-main\pvrecorder-main\sdk\python>

**Comment by ErisMik** [comment]
Just verifying that it's failing at the expected place. This looks to indeed be a miniaudio audio issue. Because this is out of scope of Picovoice, I can't provide too much help. 

To debug here you can build the base pvrecorder C demo (instructions on the main [readme](https://github.com/Picovoice/pvrecorder#readme)) with some logging in [pvrecorder.c](https://github.com/Picovoice/pvrecorder/blob/main/src/pv_recorder.c) and run it. That should help you determine what miniaudio is throwing.

You can also go to [miniaudio](https://github.com/mackron/miniaudio) itself and see if you can run one of the examples there.

If you confirm that you have miniaudio working without issues I can continue to dig into it.

**Comment by rickmini** [comment]
i understand.
heres some more info for you

i uninstalled and disable all of the laptops audio drivers. hp says it
doesnt make win 11 drivers and the intel driver supplied is from 2021

audacity which is available cross platform wont run either and fails the
same way but gives an explanation. It says that failed due to invalid
driver/hardware

so thanks for trying, i guess im going to have to wait for updated drivers

**Comment by ErisMik** [comment]
That is unfortunate to hear. Closing the issue then.
