### ISSUE TITLE
Segmentation fault on recorder.stop() after recorder.read() fails

### ISSUE THREAD

**Issue by chm-fp-robotics** [Picovoice/pvrecorder#49]
I have the following test program that simply calls "pvrecorder" (version 1.1.1) functions in Python:

```
    recorder = pvrecorder.PvRecorder(-1, 16000)
    recorder.start()
    try:
        while True:
            recorder.read()
    except Exception as error:
        print(f"{type(error).__name__}: {error}")
        recorder.stop()
        recorder.delete()
```

Now, I have a local setup with Ubuntu 22.04 and Python 3.10, and when I run this code it works fine, and when I unplug the microphone on run-time it properly prints the expected "OSError: Failed to read from device" that I can further handle in my program.

The issue is, that when I do the very same thing in my Docker setup with Ubuntu 20.04 and Python 3.8, the expected OSError is followed by tons of "[WARN] Overflow - reader is not reading fast enough." prints, concluded by a "Segmentation fault (core dumped)".

It seems to me as if the behaviour in these two setups is different. The local setup seems to handle everything the way it's supposed to be, while the recorder in the Docker setup seems to continue reading internally when the read() function is being interrupted by the microphone being plugged out. Hence to me this sounds like an issue of the recorder module, and not of my setup. But I may be wrong. Can you point me in the correct direction on how I can properly handle this issue? I need to avoid that my program crashes on microphone unplugging.

**Comment by kenarsa** [comment]
I think this can be a docker issue as it probably doesn't think the microphone is unplugged. You can build `pvrecorder` from the source and put some debug logs in it to see why this happens. Happy to help out once you pinpoint it a bit more.

**Comment by chm-fp-robotics** [comment]
Thank you for the quick response. This sounds very plausible, though I don't think I'll get the time to fix this myself anytime soon. We'd rather prevent the microphone from being unpluggable in our setup ;)

**Comment by kenarsa** [comment]
got it. closing for now then. re-open as needed.
