### ISSUE TITLE
 `logSilence` parameter

### ISSUE THREAD

**Issue by eouia** [Picovoice/pvrecorder#50]
Hi, 

I'm using your pvrecorder node SDK.
I've found `logSilence` parameter on `.process()` function.
What is the purpose of that parameter?
Is it related to `end-of-utterance`? Is there any way to use that event in `pvrecorder` ?

What I want is;
auto-release of `pvrecorder` on `end-of-utterance` alone. I know `Cheetah` or `Rhino` can detect silence/endpoint also, but what I want is simply recording audio to file so I don't need STT or STI. 
Of course, You have `Cobra` also, but it doesn't support NodeJS yet. 

Or, is there a way to judge silence with `frame(int16Array??)` data - the result of `.process()`? I'm not good at handling audio. Any hint will be a great help to me.

**Comment by kenarsa** [comment]
`logSilence` is meant to detect if your microphone is turned off or quiet. It is a debugging feature. It only looks at the volume of audio received and has nothing to do with voice activity detection.

Your best bet is to use Cobra VAD. But you are correct that it doesn't have NodeJS support yet. If you want you can submit a PR for Cobra and add Node SDK. Then we can look into it and merge it in :)
