### ISSUE TITLE
Rust SDK does not work, even demo is not working

### ISSUE THREAD

**Issue by Priler** [Picovoice/pvrecorder#51]
Hey!
Coming from Rust SDK docs and it's not working.

The error I get:
```
   --> src\main.rs:5:25
    |
5   |     let audio_devices = Recorder::get_audio_devices();
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^-- an argument of type `&Recorder` is missing
```

Seems that this method requires object of type `&Recorder` to be passed, but there's nothing about it in the Rust SDK docs.
And even if so, how to create this object?
There's nothing in docs either.

Creating an instance of `Recorder` requires some kind of `inner: Arc<RecorderInner>`.
But `RecorderInner` cannot be imported from `pv_recorder` scope.
So ... I've had to analyze source code of this crate.

And came up with this code seems to be working.
```
use pv_recorder::{RecorderBuilder};

fn main() {

    let rec = RecorderBuilder::default();
    let rec_inner = rec.init().unwrap();

    let audio_devices = rec_inner.get_audio_devices();

    println!("List of audio devices: {audio_devices:?}");
}
```

But there's nothing about it not in the Rust SDK docs nor in examples.
Even the code from Rust SDK examples also don't work and don't compile.
This is the error I get with the provided example:
```
  |
5 |     let audio_devices = RecorderBuilder::default().get_audio_devices();
  |                                                    ^^^^^^^^^^^^^^^^^ method not found in `RecorderBuilder`
```

Like ... it's only me or nobody even tested this code?
...

The Rust version I'm using is `rustc 1.68.2 (9eb3afe9e 2023-03-27)`.
I hope it will be fixed, thanks!

**Comment by ErisMik** [comment]
It appears that the package in the repo and the package on `crates.io` were out of sync. I've released a new version of the package. Please update to [`pv_recorder = "1.1.1"`] (https://crates.io/crates/pv_recorder/1.1.1), the newly published docs and examples now match the published package.

**Comment by Priler** [comment]
Year it works now, thanks.
