### ISSUE TITLE
Doesn't working with electron forge (DLL initialization routine failed)

### ISSUE THREAD

**Issue by joaomrsouza** [Picovoice/pvrecorder#76]
I'm trying to build an application with voice commands in electron, so i've made a test with picovoice packages for nodejs and it works well on default nodejs environment, but when i tried to use it with electron it gives me this error.

```
Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\Projetos\elect-forge-test\node_modules\@picovoice\pvrecorder-node\lib\windows\amd64\pv_recorder.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:1822)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at <static_initializer> (D:\Projetos\elect-forge-test\node_modules\@picovoice\pvrecorder-node\dist\pv_recorder.js:23:26)
    at Object.<anonymous> (D:\Projetos\elect-forge-test\node_modules\@picovoice\pvrecorder-node\dist\pv_recorder.js:17:18)
```

Already tried to use eletron rebuild and electron forge to build the packages with DLLs, but still no progress.

So, it's possible to use it with electron? How do i achieve that?

package.json
```
{
  "name": "elect-forge-test",
  "productName": "elect-forge-test",
  "version": "1.0.0",
  "description": "My Electron application description",
  "main": "src/index.js",
  "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "lint": "echo \"No linting configured\""
  },
  "keywords": [],
  "author": {
    "name": "João Marcos Rocha Souza",
    "email": "joaomarcos25@hotmail.com"
  },
  "license": "MIT",
  "dependencies": {
    "@picovoice/picovoice-node": "^2.2.1",
    "@picovoice/pvrecorder-node": "^1.2.0",
    "electron-squirrel-startup": "^1.0.0",
    "node-powershell": "^5.0.1",
    "node-speech": "^1.0.5",
    "speaker": "^0.5.4",
    "wav": "^1.0.2"
  },
  "devDependencies": {
    "@electron-forge/cli": "^6.3.0",
    "@electron-forge/maker-deb": "^6.3.0",
    "@electron-forge/maker-rpm": "^6.3.0",
    "@electron-forge/maker-squirrel": "^6.3.0",
    "@electron-forge/maker-zip": "^6.3.0",
    "@electron-forge/plugin-auto-unpack-natives": "^6.3.0",
    "electron": "25.4.0"
  }
}
```

**Comment by mrrostam** [comment]
It's expected as the Node.js SDK is explicitly built to function within the Node environment. For Electron or any browser-based environment, you might be able to use our [web-voice-processor](https://github.com/Picovoice/web-voice-processor)

**Comment by dolma** [comment]
@mrrostam I don't believe this issue should've been closed (although it's a bit too late now)

> It's expected as the Node.js SDK is explicitly built to function within the Node environment. For Electron or any browser-based environment, you might be able to use our [web-voice-processor](https://github.com/Picovoice/web-voice-processor)

Electron has 2 processes: `main` and `renderer`. The `renderer` process is indeed a web environment, but the `main` process IS a Node environment so the above explanation is unfortunately incorrect. As a Node library, I fully expect `pvrecorder` to run in Electron's `main` process, just like all other Node libraries do.

I'm also trying to use this library inside of Electron and ended up on this issue before opening my own (my issue is a different one).

_**Note**: It's likely not worth reopening this issue after a whole year but just thought I'd leave this comment here for reference._
