### ISSUE TITLE
Can't find some input audio devices

### ISSUE THREAD

**Issue by b-des** [Picovoice/pvrecorder#77]
Hi. 
Brief description: I can't find input device in the list using `porcupine_demo_mic --show_audio_devices` command. 
But I can see it using `arecord -l`. 
I attach the screenshot below
![image](https://github.com/Picovoice/pvrecorder/assets/14833882/024e0a14-e4ae-4fe9-81fd-b7a573bb98cd)

I know it might be not a problem with your library but with my device, since I use Orange PI 3 with Ubuntu.
Am I missing some utils/drivers? 
I hope you can explain me why there is such behavior. Thanks

**Comment by b-des** [comment]
Also I tried it on Raspberry PI. But got the next error:
![image](https://github.com/Picovoice/pvrecorder/assets/14833882/ef51df9d-b9f9-474b-bd81-063f791800ce)

**Comment by Safraann** [comment]
Hello, how did you solve this ? I'm running into the same issue at the moment with Google Voice Kit ?
Thanks in advance.

**Comment by b-des** [comment]
Hi @Safraann. I needed pvrecorder in order to use porcupine library, but I found the solution with pyaudio(as recorder), so basically I refused to use pvrecorder. If it's not mandatory to use it in your project and you have such cases, you can use some alternatives. Actually, it works fine with regular desktops, but in more narrow cases it can be not suitable

**Comment by b-des** [comment]
As for second issue I posted above - it turned out that for 32 bit OS it doesn't work, so I installed arm64 and it started working

**Comment by Safraann** [comment]
Hello, thanks a lot for your help. Installed 64 bits architecture and its working fine now.
