### ISSUE TITLE
PVRECORDER - Failed to read from device

### ISSUE THREAD

**Issue by Sebastian1771** [Picovoice/pvrecorder#78]
Hi,

i am working with Rapsberry Pi Zero 2 with Raspbian 11 with a iqaudio header for the Zero.

Programming with Python 3.9.2-3.

I installed pvrecorder / pvrecorderdemo 1.2.0

Microphone/speaker with arecord / aplay work perfectly fine. Also vosk works perfectly.

So it seems there is something on pvrecorder which does not allowto acces the Built-in Audio device which is why i'm writing it here as an issue. Same happens if called via porcupine.

> **pv_recorder_demo --show_audio_devices**
index: 0, device name: Monitor of Built-in Audio Stereo
index: 1, device name: Built-in Audio Stereo

> **pv_recorder_demo --audio_device_index 1 --output_wav_path ./testpvrec.wav**
pvrecorder version: 1.2.0
Using device: Built-in Audio Stereo
Traceback (most recent call last):
  File "/usr/local/bin/pv_recorder_demo", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/pvrecorderdemo/pv_recorder_demo.py", line 64, in main
    frame = recorder.read()
  File "/usr/local/lib/python3.9/dist-packages/pvrecorder/_pvrecorder.py", line 178, in read
    raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to read from device.")
OSError: Failed to read from device.

Help is very much appreciated.

**Comment by Sebastian1771** [comment]
Thanks a lot for the promt reply. Running your script from my desktop gave the identical issue.

> =============` RESTART: /home/sebastian/Desktop/pv_recorder_demo.py =============
pvrecorder version: 1.2.0
Using device: Built-in Audio Stereo
Traceback (most recent call last):
  File "/home/sebastian/Desktop/pv_recorder_demo.py", line 77, in <module>
    main()
  File "/home/sebastian/Desktop/pv_recorder_demo.py", line 64, in main
    frame = recorder.read()
  File "/usr/local/lib/python3.9/dist-packages/pvrecorder/_pvrecorder.py", line 178, in read
    raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to read from device.")
OSError: Failed to read from device.

I added my Airpods and again it worked automatically with arecord / aplay. 

>sebastian@raspberrypi:~/Desktop $ pv_recorder_demo --show_audio_devices
index: 0, device name: Monitor of Built-in Audio Stereo
index: 1, device name: Built-in Audio Stereo
index: 2, device name: Monitor of AirPods Max

Again identical error message appears.

**Comment by ksyeo1010** [comment]
can you run it with the device index set? `pv_recorder_demo --audio_device_index 2`

**Comment by Sebastian1771** [comment]
Tried this already and it did produce the exact same error:

> sebastian@raspberrypi:~/Desktop $ python3 pv_recorder_demo.py --audio_device_index 2
pvrecorder version: 1.2.0
Using device: Monitor of AirPods Max
Traceback (most recent call last):
  File "/home/sebastian/Desktop/pv_recorder_demo.py", line 77, in <module>
    main()
  File "/home/sebastian/Desktop/pv_recorder_demo.py", line 64, in main
    frame = recorder.read()
  File "/usr/local/lib/python3.9/dist-packages/pvrecorder/_pvrecorder.py", line 178, in read
    raise self._PVRECORDER_STATUS_TO_EXCEPTION[status]("Failed to read from device.")
OSError: Failed to read from device.

Any other idea what could be the reason?

**Comment by ksyeo1010** [comment]
Don't really know what your config.txt changes are, are those changes that affect the pi overall? if so can you try with the original config? Also are you in a 32bit or 64bit os (can you provide us more info about ur system in general)

**Comment by Sebastian1771** [comment]
I set up raspbian bullseye from scratch (32bit) and just ordered an usb microphone to make sure the error is not connected to the iqaudio card. Will let you know as soon as I had a chance to try.

**Comment by Sebastian1771** [comment]
I set up raspbian bullseye from scratch (32bit) and just ordered an usb microphone to make sure the error is not connected to the iqaudio card. Will let you know as soon as I had a chance to try.

**Comment by Sebastian1771** [comment]
Update: The problem seemed to be the iqaudio zero audio hat. I wrote the rasbian image from scratch used an external usb mic - et voilà - pvrecorder / porcupine / cheetah worked without any issue. This will be the way to go now as i won't be able to find the reason why the hat was not compatible with pvrecorder.
I herewith close this issue.
