### ISSUE TITLE
Bug when working with linux

### ISSUE THREAD

**Issue by TheBestWorldProgrammer** [Picovoice/pvrecorder#80]
string? directoryName = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location); in GetLibraryPath return null when application is published (Linux). Maybe is worth using AppDomain.CurrentDomain.BaseDirectory

**Comment by TheBestWorldProgrammer** [comment]
Published Application, .NET 7, AvaloniaUI, When I try to run a published application on linux, it falls into an error, since Assembly.Location returns null (https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#api-incompatibility     API incompatibility)

**Comment by ErisMik** [comment]
Thanks for the report, I've identified the issue and we are publishing the fix. I'll comment here when the fixed package is live.

**Comment by ErisMik** [comment]
@TheBestWorldProgrammer Fixed package should be published, please try package version `1.2.3`. Closing issue but feel free to open another one if you run into any additional issues.
