### ISSUE TITLE
Go SDK How to determine end of voice

### ISSUE THREAD

**Issue by simon28082** [Picovoice/pvrecorder#84]
Thank you very much to the developers and contributors of Picovoice team, I am a go sdk user, I want to read the microphone constantly, but I want to end the current microphone listening at the end of a sentence when there are no new words for about 1-2 judgments, I looked up the API, and found there is no option, can team provide me some help and suggestions? This is very important for me, thanks a lot!

**Comment by simon28082** [comment]
@mrrostam thanks reply, but cobra not go sdk

**Comment by mrrostam** [comment]
I noticed that you opened another issue on the Cobra repository, so I will close this one, as it is no longer relevant to `pvrecorder`.
