### ISSUE TITLE
Picovoice Documentation Issue (/docs/api/pvrecorder-go/)

### ISSUE THREAD

**Issue by nfaraji2002** [Picovoice/pvrecorder#88]
@laves 
Hi,

I am using Pvrecorder according to https://pypi.org/project/pvrecorder/ and wrote this simple code:

%%%%%%%%%%%%%%%%%%%%%%%%%%%
from pvrecorder import PvRecorder
devices = PvRecorder.get_available_devices()
recorder = PvRecorder(frame_length=512, device_index=0)
recorder.start()
while True:
    frame = recorder.read()
    print(frame)
    # process audio frame
recorder.stop()
recorder.delete()
%%%%%%%%%%%%%%%%%%%%%%%%
but it always prints a vector of zeros [0,0,0,0,0,0,.....]. The volume of the microphone has been set to 100% and it records audios by "arecord" command.  What is the problem?

Thanks,

**Comment by laves** [comment]
Are you sure you are using the correct device index? I see you've passed `device_index=0`, but the device index for your microphone may be different. Ensure you've tried all the available options from `get_available_devices()`. 

If none of your available devices work then it may be something about the environment you're running it on. Let me know what OS/machine you're running it on.

**Comment by nfaraji2002** [comment]
I am using waveshare usb to audio soundcard on raspberry pi 4. I tried the other device indexs and I got the error. With device index 0, the code runs without error and it says listening, but the frame vector is always 0. When I run arecord -l command, there is  one capture device which is also default. Is it required any other settings with alsa.conf?

**Comment by laves** [comment]
`device_index=-1` sets the device to default - have you tried that?

**Comment by nfaraji2002** [comment]
Yes, I think the problem is with raspberry, but I don not know how to resolve it. I have used pvrecorder on my computer and it works fine.

**Comment by laves** [comment]
Unfortunately, we can't help debug audio configuration/hardware issues as they are out of the scope of this repo. Under the hood pvrecorder uses [miniaudio](https://github.com/mackron/miniaudio) - so I'd suggest searching their issues or opening a new one.
