### ISSUE TITLE
Rust bindings: dlls are not copied into the release directory when compiling

### ISSUE THREAD

**Issue by denizsincar29** [Picovoice/pvrecorder#90]
Hello. When I try to compile my [rust program](github.com/denizsincar29/dtmf_rust), I got no dlls in the release directory. So I just copied the exe and gave to my friend. He said that it cannot find the dll, but on my computer where I compiled, it works in all folders where I copy my exe. What is happening?
Additionally I installed pvrecorder for python via pip, just in case...
What to do? Where are the DLLS?   
Thank you.

**Comment by ksyeo1010** [comment]
There are ddls associated, if you want to move binaries, you should pass the whole release directory.

**Comment by ErisMik** [comment]
Just to chime in, when using cargo to build locally the DLLs are copied to a place where the executable can access them and the internal path points to them. If you are planning to distribute the executable (say to your friend) you need to use the [.library_path()](https://docs.rs/pv_recorder/latest/pv_recorder/struct.PvRecorderBuilder.html#method.library_path) function of the builder class to put the path to the [DLL](https://github.com/Picovoice/pvrecorder/tree/main/lib/windows/amd64), which also needs to be distributed to your friend.

**Comment by denizsincar29** [comment]
well, i did a cargo make script that does distribute the dll...
