### ISSUE TITLE
pvrecorder not working on the Jetson Orin Nano - RuntimeError: Current system is not supported.

### ISSUE THREAD

**Issue by jedld** [Picovoice/pvrecorder#92]
Running this on the Jetson Orin Nano throws an error: RuntimeError: Current system is not supported.

Digging into this it seems pvrecorder/resources/scripts/platform.sh needs to be updated to correctly identify the new CPU used in the Orin series.

Here is the cpuinfo:

cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 62.50
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp uscat ilrcpc flagm paca pacg
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd42
CPU revision	: 1

processor	: 1
BogoMIPS	: 62.50
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp uscat ilrcpc flagm paca pacg
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd42
CPU revision	: 1

processor	: 2
BogoMIPS	: 62.50
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp uscat ilrcpc flagm paca pacg
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd42
CPU revision	: 1

processor	: 3
BogoMIPS	: 62.50
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp uscat ilrcpc flagm paca pacg
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd42
CPU revision	: 1

processor	: 4
BogoMIPS	: 62.50
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp uscat ilrcpc flagm paca pacg
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd42
CPU revision	: 1

processor	: 5
BogoMIPS	: 62.50
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp uscat ilrcpc flagm paca pacg
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd42
CPU revision	: 1

Error Trace:

    for index, device in enumerate(PvRecorder.get_available_devices()):
  File "/usr/local/lib/python3.10/dist-packages/pvrecorder/_pvrecorder.py", line 231, in get_available_devices
    get_available_devices_func = PvRecorder._get_library().pv_recorder_get_available_devices
  File "/usr/local/lib/python3.10/dist-packages/pvrecorder/_pvrecorder.py", line 261, in _get_library
    cls._relative_library_path = default_library_path()
  File "/usr/local/lib/python3.10/dist-packages/pvrecorder/_pvrecorder.py", line 33, in default_library_path
    raise RuntimeError("Current system is not supported.")
RuntimeError: Current system is not supported.

**Comment by ErisMik** [comment]
pvrecorder is intended to support Picovoice demos and products, although others have found success using it for their own projects. Therefore we can only officially support platforms that Picovoice software runs on. Unfortunately, this does not include the Jetson Orin Nano at the moment.

If you are using pvrecorder in your own project, feel free to fork and make the updates that you need to get it to work on your platform.

 If this is a commercial application with the budget allocated, feel free to contact the [sales team](https://picovoice.ai/pricing/).
