### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by Denis-Kazakov** [Picovoice/pvrecorder#95]
What are output values? What is their maximum possible range?

**Comment by ErisMik** [comment]
Is there a specific part of the `pvrecorder` api you are referring to?  In general `pvrecorder` returns 16bit signed integer PCM as the audio. So each PCM has a range of -32,768 to 32,767. Frame length has to be larger than 0. It has no explicit maximum, but keep in mind that it creates buffers, etc. so there are real limits with regards to maximum array length and memory usage.

**Comment by Denis-Kazakov** [comment]
Sorry for not making it clear. I use the commands from the Python example to record microphone sound:
```
recorder = PvRecorder(frame_length=512)
...
 frame = recorder.read()
```
In my experiment, min/max values that I got were ~ -2500 to +2500. I wanted to normalize and process each frame separately (but all to the same scale), one by one, so needed to know the max possible range.

**Comment by ErisMik** [comment]
I see. Well then as mentioned the actual maximum range is -32,768 to 32,767 (16 bit signed integer). In practice the values won't reach that as it depends on the audio driver, microphone, gain, etc. Hope that helps!

**Comment by Denis-Kazakov** [comment]
Yes, that answers my question. Thank you!
