### ISSUE TITLE
C demo does not work

### ISSUE THREAD

**Issue by Vubni** [Picovoice/pvrecorder#97]
C demo doesn't work when I try to compile the last command `cmake --build build` it comes out to me:
```cmake --build build
[ 50%] Linking C executable pv_recorder_demo.exe
E:/g++/pvrecorder/pvrecorder/demo/c/../../lib/windows/amd64/libpv_recorder.dll: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
CMakeFiles\pv_recorder_demo.dir\build.make:98: recipe for target 'pv_recorder_demo.exe' failed
mingw32-make.exe[2]: *** [pv_recorder_demo.exe] Error 1
CMakeFiles\Makefile2:81: recipe for target 'CMakeFiles/pv_recorder_demo.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/pv_recorder_demo.dir/all] Error 2
Makefile:89: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
```
Maybe I'm doing something wrong, I planned to use the library in C++, but so far I can't connect it, is it possible?

**Comment by mrrostam** [comment]
I was unable to reproduce your result. Does the log correspond to the C demo we have in our repository or is it from your code?

**Comment by Vubni** [comment]
@mrrostam The error appears when following the C demo and all demo files, I did not replace anything

The system is Windows

**Comment by mrrostam** [comment]
Since everything seems to be working correctly on our end, could you please run the command `gcc --version` and share the output so we can determine which version of MinGW you are using?

**Comment by mrrostam** [comment]
noticed your gcc is pretty old. Is it possible for you to try a new version from [here](https://winlibs.com/)?

**Comment by Vubni** [comment]
That was really the problem, now demo c is working!

I think, since I have indicated the heading 'Demo C does not work', it is better to close this application and create a new one in C++, after a series of experiments, thank you!
